name: Build and publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel

    - name: Build distributions
      run: |
        python -m build --sdist --wheel .
        ls -l dist/

    - name: Check distribution contents
      run: |
        pip install twine
        twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: dist
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - build
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.11.0
      with:
        skip-existing: true
